 
 
 CREATE TABLE JOB (
 JNO NUMBER(2) PRIMARY KEY,
 JNAME VARCHAR(30) NOT NULL
 );
 
 CREATE TABLE PERSON(
    NO NUMBER(5) PRIMARY KEY,
    NAME VARCHAR(30) NOT NULL,
    JNO NUMBER(2) REFERENCES JOB(JNO),
    KOR NUMBER(3),
    ENG NUMBER(3),
    MAT NUMBER(3)
);

DROP TABLE JOB;
DROP TABLE PERSON;
CREATE SEQUENCE PERSON_NO_SQ MAXVALUE 9999;
DROP SEQUENCE PERSON_NO_SQ;

INSERT INTO job VALUES (10, '배우');
INSERT INTO job VALUES (20, '가수');
INSERT INTO job VALUES (30, 'mc');

SELECT * FROM JOB;
SELECT * FROM PERSON;

-- 1. 입력
INSERT INTO PERSON VALUES 
    (PERSON_NO_SQ.NEXTVAL,'정우성', 
        (SELECT JNO FROM JOB WHERE JNAME='배우'), 90,90,90);
INSERT INTO PERSON VALUES 
    (PERSON_NO_SQ.NEXTVAL,'박세영', 
        (SELECT JNO FROM JOB WHERE JNAME='배우'), 80,90,80);
INSERT INTO PERSON VALUES 
    (PERSON_NO_SQ.NEXTVAL,'배수지', 
        (SELECT JNO FROM JOB WHERE JNAME='가수'), 20,90,90);
        
COMMIT;

-- 2 : 1 송혜교(5번) 배우 100 100 100 300 (총점순 내림차순)
SELECT NAME ||'('|| NO || ' 번)' NAME, JNAME, KOR, ENG, MAT, KOR+ENG+MAT SUM
    FROM PERSON P, JOB J
    WHERE P.JNO=J.JNO AND JNAME='배우'
    ORDER BY SUM DESC; --FROM절에 들어갈 서브쿼리

SELECT ROWNUM RANK,S.*
    FROM (SELECT NAME ||'('|| NO || ' 번)' NAME, JNAME, KOR, ENG, MAT, KOR+ENG+MAT SUM
    FROM PERSON P, JOB J
    WHERE P.JNO=J.JNO AND JNAME='배우'
    ORDER BY SUM DESC) S; --자바 2번 기능에 쓸 메인쿼리
    
SELECT ROWNUM RANK,S.*
    FROM (SELECT NAME ||'('|| NO || ' 번)' NAME, JNAME, KOR, ENG, MAT, KOR+ENG+MAT SUM
    FROM PERSON P, JOB J
    WHERE P.JNO=J.JNO
    ORDER BY SUM DESC) S; --자바 3번 기능에 쓸 메인쿼리
    
SELECT * FROM PERSON;

--콤보박스에 넣을 직업 리스트.
SELECT JNAME FROM JOB;






