

-- 조건① CUSTOMER 테이블이 있을 시, 테이블을 삭제하고 테이블을 생성하시오
DROP TABLE CUSTOMER;
DROP TABLE CUS_LEVEL;

--조건③ CUS_LEVEL 테이블은 필드별로 다음의 제약조건을 지킨다
CREATE TABLE CUS_LEVEL(
levelno NUMERIC(5) PRIMARY KEY,
levelname VARCHAR(20) NOT NULL
);

-- 조건② CUSTOMER 테이블은 필드별로 다음의 제약조건을 지킨다.
CREATE TABLE CUSTOMER(
cno  NUMBER(4) PRIMARY KEY,
cname VARCHAR(20) NOT NULL,
joindate DATE DEFAULT SYSDATE,
phone VARCHAR(30) UNIQUE,
point NUMBER(38),
levelno NUMBER(5)REFERENCES CUS_LEVEL(levelno)
);

--조건④ CUSTOMER 테이블의 CNO번호는 시퀀스(CUS_SQ)를 생성한 뒤 자동생성 번호로 입력되도록 한다.
CREATE SEQUENCE CUS_SQ
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 9999
    MINVALUE 1
    NOCYCLE
    NOCACHE;
    
DROP SEQUENCE CUS_SQ;

-- 데이터 입력할 것
INSERT INTO CUS_LEVEL VALUES(1, 'VVIP');
INSERT INTO CUS_LEVEL VALUES(2, 'VIP');
INSERT INTO CUS_LEVEL VALUES(3, 'NORMAL');
INSERT INTO CUS_LEVEL VALUES(4, 'BLACK');

INSERT INTO CUSTOMER VALUES(CUS_SQ.NEXTVAL,'홍길동',TO_DATE(20171017),'010-9999-9999',300,1);
INSERT INTO CUSTOMER (cno,cname,joindate,phone,point,levelno) VALUES(CUS_SQ.NEXTVAL,'이철수',TO_DATE(20160906),'010-9999-9888',NULL,2);
INSERT INTO CUSTOMER (cno,cname,joindate,phone,point,levelno) VALUES(CUS_SQ.NEXTVAL,'홍길순',TO_DATE(20160907),'010-9999-7777',50,3);

SELECT * FROM CUSTOMER;
SELECT * FROM CUS_LEVEL;
DESC CUSTOMER;
DESC CUS_LEVEL;
