
--1. 드랍
DROP TABLE CART;
DROP TABLE ORDER_DETAIL;
DROP TABLE ORDER_;
DROP TABLE ITEM;
DROP TABLE CUSTOMER;

--2. 테이블 생성

CREATE SEQUENCE SEQ_NO MAXVALUE 99999999;

CREATE TABLE CUSTOMER(
CUSNO VARCHAR(10)PRIMARY KEY,
CUSNAME VARCHAR(20),
CUSADD  VARCHAR(30),
CUSTEL  VARCHAR(10)
);

CREATE TABLE ITEM(
ITEMCODE VARCHAR(4) PRIMARY KEY,
ITEMNAME VARCHAR(20),
UNITPRICE NUMBER(8),
STOCK NUMBER(3),
PRICE NUMBER(8)
);

CREATE TABLE ORDER_(
ORDERNO NUMBER(8) PRIMARY KEY,
CUSNO VARCHAR(10) REFERENCES CUSTOMER(CUSNO),
ORDER_ADD  VARCHAR(30),
ORDER_TEL  VARCHAR(10),
ORDER_DATE DATE DEFAULT SYSDATE
);

CREATE TABLE ORDER_DETAIL(
SEQ_NO NUMERIC(8) PRIMARY KEY,
ORDERNO NUMBER(8) REFERENCES ORDER_(ORDERNO),
ITEMCODE VARCHAR(4) REFERENCES ITEM(ITEMCODE),
CART_AMOUNT NUMBER(3),
FINAL_PRICE NUMBER(8)
);

CREATE TABLE CART(
SEQ_NO NUMERIC(8) PRIMARY KEY,
CUSNO VARCHAR(10)REFERENCES CUSTOMER(CUSNO),
ITEMCODE VARCHAR(4) REFERENCES ITEM(ITEMCODE),
CART_AMOUNT  NUMERIC(3),
FINAL_PRICE NUMERIC(8)
);


