-- [Iv] 단일행함수
-- 함수= 단일행 함수+그룹함수
SELECT ENAME, TO_CHAR(HIREDATE, 'YY"년"MM"월"DD"일" DY"요일"')
    FROM EMP;
SELECT ENAME, INITCAP(ENAME) FROM EMP;
SELECT DEPTNO, SUM(SAL) FROM EMP GROUP BY DEPTNO;

SELECT SUM(SAL) FROM EMP; --그룹함수의 예
--EX. 숫자관련함수, 문자 관련 함수, 형변환 함수, NVL(), ETC....
--(1) 숫자함수
SELECT ABS(-9)=FROM DUAL;
DESC DUAL ; 오라클에서 제공하는 1행 1열짜리 더미 테이블
SELECT ABS(-9) FROM DUAL; 절대값
SELECT FLOOR (34.5678) FROM DUAL; --소수점에서 내림
SELECT FLOOR (34.5678)*10 /10 FROM DUAL;
SELECT TRUNC(34.5678) FROM DUAL; --소수점에서 내림; 
SELECT TRUNC(34.5678,-1) FROM DUAL;

--EMP 테이블에서 이름, 급여 십의 자리까지만 출력
SELECT ENAME, TRUNC(SAL,-2) FROM EMP; 

SELECT CEIL(34.5678) FROM DUAL; --소수점에서 올림
SELECT ROUND(34.5678) FROM DUAL; --소수점에서 반올림
SELECT ROUND(34.5678,1) FROM DUAL; --소수점 한자리에서 반올림
SELECT ROUND(34.5678,-1) FROM DUAL; --일의 자리에서 만올림

SELECT 10/4 FROM DUAL;

SELECT FLOOR(10/4) FROM DUAL;
SELECT MOD(9,2) FROM DUAL; --나머지 연산
SELECT MOD('9',2) FROM DUAL; --나머지 연산
--홀수달에 입사한 직원들의 모든 필드를 출력
SELECT * FROM EMP 
    WHERE MOD(TO_CHAR(HIREDATE,'MM'),2)=1;
    
    
--(2) 문자 함수
SELECT UPPER('abcABC') FROM DUAL;
SELECT LOWER('abcABC') FROM DUAL;  
SELECT INITCAP('abcABC') FROM DUAL;
--JOB이 MANAGER인 직원의 모든 필드
SELECT * FROM EMP WHERE UPPER(JOB) = 'MANAGER';
SELECT EMPNO,INITCAP(ENAME) FROM EMP;
--문자 연결
SELECT 'AB'||'CD'||'EF'||'GH' FROM DUAL;
SELECT CONCAT(CONCAT('AB','CE'), CONCAT('EF','GH'))FROM DUAL;
--XXX는 XX다(이름은 JOB이다)
SELECT ENAME|| '은' ||JOB||'이다' FROM EMP;
SELECT CONCAT(CONCAT(ENAME,'은'),CONCAT(JOB,'이다')) FROM EMP;
--SUBSTR(STR, 시작 위치, 문자 갯수) 첫번째 위치가 1
--SUB STRB(STR,시작 위치, 문자 바이트 수)
SELECT SUBSTR('WELCOM TO ORACLE',3,2) FROM DUAL; --LC(3번째부터 2개)
SELECT SUBSTRB('WELCOM TO ORACLE',3,2) FROM DUAL; --3번재부터 2BYTE
SELECT SUBSTR('데이터베이스',4,3) FROM DUAL; 
SELECT SUBSTRB('데이터베이스',4,3) FROM DUAL; --4번째 BYTE부터 3BYTE
--영어는 한 문자가 1 BYTE, 한글 한문자가 3BYTE
--9월에 입사한 사원의 모든 필드
SELECT * FROM EMP WHERE SUBSTR(HIREDATE,4,2)=9;
--글자가 있으면
--123456
---6,-5,-4,-3,-2,-1
--이렇게 뒤에서부터도 셀 수 있다
SELECT SUBSTR('010-99-9999',-4,4) FROM DUAL;
--9일에 입사한 사원의 모든필드
SELECT * FROM EMP WHERE SUBSTR(HIREDATE,-1,2)=9;

SELECT LENGTH('ABCD')FROM DUAL; --문자 개수
SELECT LENGTHB('ABCD')FROM DUAL; --문자 개수
SELECT LENGTH('오라클')FROM DUAL; --문자 개수
SELECT LENGTHB('오라클')FROM DUAL; --문자 개수
-- INSTR(str, 찾을 글자); str에서 찾을 글자의 위치
SELECT INSTR('ABCABC','B') FROM DUAL; --2
SELECT INSTR('ABCABC','B',3) FROM DUAL; --5
--9월/9일에 입사한 사원(INSTR이용)
SELECT * FROM EMP WHERE INSTR(HIREDATE,'09')=4;
SELECT * FROM EMP WHERE INSTR(HIREDATE,'09')=7;

--LPAD(문자, 자리수, '*') 문자를 자리수만큼 확보하고 왼쪽 빈자리에 지정 문자 넣음
SELECT LPAD('ORACLE',20,'#') FROM DUAL;
SELECT RPAD('ORACLE',20,'*') FROM DUAL;
SELECT ENAME, LPAD(SAL,6,'*') FROM EMP;
 
--사번, S****(이름은 앞 한문자만 출력하고 나머지는 *출력)
SELECT EMPNO,RPAD (SUBSTR(ENAME,1,1),LENGTH(ENAME),'*') FROM EMP;
--7369(사번), S****(이름), 80/12/**(입사일) 출력
SELECT EMPNO, RPAD (SUBSTR(ENAME,1,1),LENGTH(ENAME),'*') NAME, RPAD(SUBSTR(HIREDATE,1,6),LENGTH(HIREDATE),'*')  FROM EMP;
--7369(사번), ****h(이름), 80/12/**(입사일) 출력
SELECT EMPNO, LPAD (SUBSTR(ENAME,-1,1),LENGTH(ENAME),'*'), RPAD(SUBSTR(HIREDATE,1,6),LENGTH(HIREDATE),'*') FROM EMP;
--이름 세번째 자리가 r인 사원 출력
SELECT ENAME FROM EMP WHERE INSTR(ENAME,'R')=3;
SELECT ENAME FROM EMP WHERE SUBSTR(ENAME,3,1)='R';
SELECT ENAME FROM EMP WHERE ENAME LIKE '__R%';

SELECT TRIM('   ORACLE DB       ') DB FROM DUAL;
SELECT RTRIM('   ORACLE DB       ') DB FROM DUAL;
SELECT LTRIM('   ORACLE DB       ') DB FROM DUAL;

SELECT REPLACE (ENAME,'A','XX') FROM EMP;

--(3) 날짜 관련 예약어, 함수
SELECT SYSDATE FROM DUAL;
SELECT TO_CHAR(SYSDATE,'YY-MM-DD HH:MI:SS') FROM DUAL;
SELECT SYSDATE-1 어제, SYSDATE 지금, SYSDATE +1 내일 FROM DUAL;

--14일 후
SELECT SYSDATE+14 FROM DUAL;

--이름, 입사일, 근무일자
SELECT ENAME, HIREDATE, FLOOR(SYSDATE - HIREDATE)근무일자 FROM EMP;

--이름, 입사일, 근무주수, 근무년수 출력
SELECT ENAME, FLOOR((SYSDATE - HIREDATE)/7) 근무주수,FLOOR((SYSDATE - HIREDATE)/365) 근무년수 FROM EMP;

--MONTHS_BETWEEN() 특정한 두 시점 사이의 개월수
--이름, 입사일, 근무월수
SELECT ENAME, HIREDATE, TRUNC(MONTHS_BETWEEN(SYSDATE, HIREDATE)) FROM EMP;

--ADD_MONTHS(특정날짜, 개월수) 특정한 날짜로부터 몇개월 후의 시점
--이름, 입사일, 수습기간만료일(수습기간은 6개월)
SELECT ENAME, HIREDATE, ADD_MONTHS(HIREDATE, 6) FROM EMP;

--NEXT_DAY(특정 날짜, '수') 특정 날짜로부터 처음 도래하는 수요일. 
SELECT NEXT_DAY(SYSDATE,'토') FROM DUAL;

--LAST_DAY(특정날짜) ; 특정 날짜인 달의 말일
--이름, 입사일, 월급날(월급은 말일)
SELECT ENAME, HIREDATE, LAST_DAY(HIREDATE) FROM EMP;

--ROUND; 날짜 반올림, TRUNC: 날짜 버림
SELECT ROUND(SYSDATE-30, 'YEAR') FROM DUAL; --결과 1월1일
SELECT ROUND(SYSDATE-30, 'MONTH') FROM DUAL; --결과 1일
SELECT ROUND(SYSDATE, 'DAY') FROM DUAL; --결과 일요일
SELECT ROUND(SYSDATE)FROM DUAL; --결과: 가까운 0시

SELECT TRUNC(SYSDATE-30, 'YEAR') FROM DUAL; --지난 1월1일
SELECT TRUNC(SYSDATE-30, 'MONTH') FROM DUAL; --지난 1일
SELECT TRUNC(SYSDATE, 'DAY') FROM DUAL; --지난 일요일 
SELECT TRUNC(SYSDATE)FROM DUAL; --결과는 지난 0시

--EX1. 이름, 입사일, 입사일달의 1일
SELECT ENAME, HIREDATE, TRUNC(HIREDATE,'MONTH') FROM EMP;

--EX2. 이름, 입사일, 월급날(25일)
--SELECT ENAME, HIREDATE, TRUNC(HIREDATE,'MONTH')+24 FROM EMP; 틀렸다
SELECT ENAME, HIREDATE, ROUND(HIREDATE-9,'MONTH')+24 FROM EMP;

--EX3. 이름, 입사일, SAL(월급), 이때까지 받은 월급 합
SELECT ENAME, HIREDATE, SAL,  TRUNC(MONTHS_BETWEEN(SYSDATE, HIREDATE))*SAL 누적월급 FROM EMP;

--EX4. 이름, 입사일, SAL, COMM, 이때까지 받은 연봉(SAL*12+COMM)
SELECT ENAME, HIREDATE, SAL, COMM, FLOOR((SYSDATE - HIREDATE)/365)*((SAL*12)+NVL(COMM,0)) 누적연봉 FROM EMP;
SELECT ENAME, HIREDATE, SAL, COMM, (TRUNC(MONTHS_BETWEEN(SYSDATE, HIREDATE))*SAL)+(NVL(COMM,0)*TRUNC(MONTHS_BETWEEN(SYSDATE, HIREDATE)))누적연봉 FROM EMP;


