--[VI] SUB QUERY ; QUERY 안에 QUERY가 내포

-- ★ 1. 서브쿼리의 개념

--서브쿼리 (1) 단일행서브쿼리(서브쿼리 결과가 단일행) =, >, >=, <, <=, <>
--        (2) 다중행서브쿼리(서브쿼리 결과가 2행이상) IN ANY ALL ㄴSOME ALL EXISTS등등
--SCOTT이 근무하는 부서이름 출력
SELECT DNAME FROM EMP E, DEPT D
    WHERE E.DEPTNO=D.DEPTNO AND ENAME='SCOTT';

SELECT DEPTNO FROM EMP WHERE ENAME = 'SCOTT';  --서브쿼리  
SELECT DNAME FROM DEPT 
    WHERE DEPTNO = (SELECT DEPTNO FROM EMP WHERE ENAME = 'SCOTT'); --메인쿼리
--JOB이 'MANAGER'인 사람의 부서이름
SELECT DEPTNO FROM EMP WHERE JOB ='MANAGER'; --다중행서브쿼리
SELECT DNAME FROM DEPT
    WHERE DEPTNO IN (SELECT DEPTNO FROM EMP WHERE JOB ='MANAGER'); --메인쿼리. 다중행인 경우는 =이 아닌 IN을 사용함

-- ★ 2. 단일행 서브쿼리
--회사에서 급여를 제일 많이 받는 사람의 이름과 급여
SELECT MAX(SAL) FROM EMP; --서브쿼리(단일행, 단일열)
SELECT ENAME FROM EMP WHERE SAL=(SELECT MAX(SAL) FROM EMP); --메인쿼리

--SCOTT과 같은 부서번호인 사람이름
SELECT DEPTNO FROM EMP WHERE ENAME = 'SCOTT';
SELECT ENAME FROM EMP WHERE DEPTNO =(SELECT DEPTNO FROM EMP WHERE ENAME = 'SCOTT')AND ENAME<>'SCOTT';

--SCOTT과 같은 근무지인 사람이름(50번 DZLLAS부서 홍길동을 잠시 추가입력함)
--INSERT INTO DEPT VALUES (50,'IT','DALLAS');
--INSERT INTO EMP(EMPNO, ENAME,DEPTNO) VALUES (9999, '홍', 50);

SELECT LOC FROM EMP E, DEPT D WHERE E. DEPTNO=D.DEPTNO AND ENAME = 'SCOTT';

SELECT ENAME FROM EMP E, DEPT D
    WHERE E. DEPTNO=D.DEPTNO AND LOC =(SELECT LOC 
    FROM EMP E, DEPT D 
    WHERE E. DEPTNO=D.DEPTNO AND ENAME = 'SCOTT')AND ENAME<>'SCOTT';

--탄탄다지기
--SCOTT과 같은 부서에서 근무하는 사람들의 급여 합
SELECT DEPTNO FROM EMP WHERE ENAME='SCOTT';
SELECT SUM(SAL) FROM EMP WHERE DEPTNO = (SELECT DEPTNO FROM EMP WHERE ENAME='SCOTT');

--SCOTT과 동일한 JOB을 가진 사원의 모든 정보를 출력
SELECT * FROM EMP
    WHERE JOB = (SELECT JOB FROM EMP WHERE ENAME = 'SCOTT');
    
--DALLAS에서 근무하는 사원의 이름, 부서번호를 출력
ROLLBACK; --DML명령어를 취소

SELECT ENAME, DEPTNO FROM EMP
    WHERE DEPTNO = (SELECT DEPTNO FROM DEPT WHERE LOC='DALLAS');

--SALES 부서에서 근무하는 모든 사원의 이름과 급여를 출력

SELECT ENAME, SAL FROM EMP
    WHERE DEPTNO = (SELECT DEPTNO FROM DEPT WHERE DNAME = 'SALES');
    
-- 'KING'이 직속상사인 사원의 이름과 급여를 출력
SELECT ENAME, SAL FROM EMP
    WHERE MGR=(SELECT EMPNO FROM EMP WHERE ENAME ='KING');

-- 평균급여 이하로 받는 사원의 이름, 급여를 출력
SELECT ENAME, SAL FROM EMP
    WHERE SAL<=(SELECT AVG(SAL) FROM EMP);
    
--SCOTT과 JOB과 부서번호가 같은 직원의 모든 필드 출력(다중열 서브쿼리)
SELECT * FROM EMP 
WHERE JOB=(SELECT JOB FROM EMP WHERE ENAME='SCOTT')AND DEPTNO=(SELECT DEPTNO FROM EMP WHERE ENAME='SCOTT') AND ENAME<>'SCOTT';

SELECT * FROM EMP 
WHERE (JOB,DEPTNO)=(SELECT JOB,DEPTNO FROM EMP WHERE ENAME='SCOTT')AND ENAME<>'SCOTT';

-- ★ 총 연습문제
--1. 사원테이블에서 가장 먼저 입사한 사람의 이름, 급여, 입사일
SELECT ENAME, SAL, HIREDATE FROM EMP WHERE HIREDATE=(SELECT MIN(HIREDATE) FROM EMP);

-- 2. 회사에서 가장 급여가 적은 사람의 이름, 급여
SELECT ENAME, SAL FROM EMP WHERE SAL=(SELECT MIN(SAL) FROM EMP);

-- 3. 회사 평균보다 급여를 많이 받는 사람의 이름, 급여, 부서코드
SELECT ENAME, SAL, DEPTNO 
    FROM EMP 
    WHERE SAL>=(SELECT AVG(SAL) FROM EMP);

--4. 회사 평균 이하의 급여를 받는 사람의 이름, 급여, 부서명
SELECT ENAME, SAL, DNAME 
    FROM EMP E, DEPT D 
    WHERE E.DEPTNO = D.DEPTNO AND SAL<=(SELECT AVG(SAL) FROM EMP);

--5. SCOTT보다 먼저 입사한 사람의 이름, 급여, 입사일, 급여 등급
SELECT ENAME, SAL, HIREDATE, GRADE 
    FROM EMP E, SALGRADE S 
    WHERE SAL >=LOSAL AND SAL <=HISAL 
    AND HIREDATE<=(SELECT HIREDATE FROM EMP WHERE ENAME='SCOTT') AND ENAME<>'SCOTT';

--6. 5번(SCOTT보다 먼저 입사한 사람의 이름, 급여, 입사일, 급여 등급)에 부서명 추가하고 
    --급여가 큰 순 정렬
SELECT ENAME, SAL, HIREDATE, GRADE, DNAME 
    FROM EMP E, SALGRADE S, DEPT D 
    WHERE E.DEPTNO=D.DEPTNO AND SAL >=LOSAL AND SAL <=HISAL AND HIREDATE<=(SELECT HIREDATE FROM EMP WHERE ENAME='SCOTT') AND ENAME<>'SCOTT'
    ORDER BY SAL DESC;

--7. 사원테이블에서 BLAKE 보다 급여가 많은 사원들의 사번, 이름, 급여를 검색
SELECT DEPTNO, ENAME, SAL
    FROM EMP
    WHERE SAL>(SELECT SAL FROM EMP WHERE ENAME = 'BLAKE');

--8. 사원테이블에서 MILLER보다 늦게 입사한 사원의 사번, 이름, 입사일을 검색하시오
SELECT DEPTNO, ENAME, HIREDATE
    FROM EMP
    WHERE HIREDATE>(SELECT HIREDATE FROM EMP WHERE ENAME = 'MILLER');

--9. 사원테이블에서 사원전체 평균 급여보다 급여가 많은 사원들의 사번, 이름, 급여를 검색
SELECT DEPTNO, ENAME, SAL
    FROM EMP
    WHERE SAL>=(SELECT AVG(SAL) FROM EMP);

--10. 사원테이블에서 CLARK와 같은 부서며, 사번이 7698인 직원의 급여보다 
        -- 많은 급여를 받는 사원들의 사번, 이름, 급여 검색
SELECT DEPTNO, ENAME, SAL
    FROM EMP
    WHERE DEPTNO=(SELECT DEPTNO FROM EMP WHERE ENAME = 'CLARK')AND SAL>=(SELECT SAL FROM EMP WHERE EMPNO ='7698');

--11.  응용심화. 사원테이블에서 CLARK와 같은 부서명이며, 사번이 7698인 직원의 급여보다 
    --  많은 급여를 받는 사원들의 사번, 이름, 급여 검색
 SELECT E.DEPTNO, ENAME, SAL
    FROM EMP E, DEPT D
    WHERE E.DEPTNO = D.DEPTNO AND DNAME=(SELECT DNAME FROM  EMP E, DEPT D WHERE  E.DEPTNO = D.DEPTNO AND ENAME = 'CLARK')AND SAL>=(SELECT SAL FROM EMP WHERE EMPNO ='7698');

--12.  사원 테이블에서 BLAKE와 같은 부서에 있는 모든 사원의 이름과 입사일자를 출력하는 SELECT문을 작성하시오.
SELECT ENAME, HIREDATE
    FROM EMP
    WHERE DEPTNO =(SELECT DEPTNO FROM EMP WHERE ENAME = 'BLAKE')AND ENAME<>'BLAKE';

--13.  사원 테이블에서 평균 급여 이상을 받는 모든 종업원에 대해서 사원번호와 이름을 출력
        --(단 급여가 많은 순으로 출력하여라.)
SELECT DEPTNO, ENAME
    FROM EMP
    WHERE SAL>=(SELECT AVG(SAL) FROM EMP)
    ORDER BY SAL DESC;

-- 여기서부터는 다중행서브쿼리, 이전은 단일행서브쿼리

--★ 3. 다중행 서브쿼리 : IN, ALL, ANY=SOME, EXISTS
-- (1) IN
-- 부서별로 입사일이 가장 늦은 사람의 부서번호, 이름, 입사일 출력
SELECT DEPTNO, MAX(HIREDATE) FROM EMP GROUP BY DEPTNO; -- 서브쿼리
SELECT EMPNO, ENAME, HIREDATE FROM EMP
    WHERE (DEPTNO, HIREDATE) IN (SELECT DEPTNO, MAX(HIREDATE) FROM EMP GROUP BY DEPTNO);
    
--급여 3000이상 받는 사원이 소속된 부서에서 근무하는 사원들의 모든 정보
SELECT * FROM EMP
    WHERE DEPTNO IN (SELECT DEPTNO FROM EMP WHERE SAL>=3000);
--(2) ALL
-- 30번 부서 사원들 중 급여를 가장 많이 받는 사원보다 더 많은 급여를 받는 사원들. 
--단일행으로는 아래와 같다.
SELECT * FROM EMP
    WHERE SAL>(SELECT MAX(SAL) FROM EMP WHERE DEPTNO=30);

SELECT * FROM EMP
    WHERE SAL> ALL(SELECT SAL FROM EMP WHERE DEPTNO=30);

--(3) ANY=SOME
SELECT * FROM EMP
    WHERE SAL> ANY(SELECT SAL FROM EMP WHERE DEPTNO=30);
SELECT * FROM EMP
    WHERE SAL> (SELECT MIN(SAL) FROM EMP WHERE DEPTNO=30);

--(4) EXISTS : 서브쿼리 결과가 존재하면 참
--직속부하가 있는 직원들의 사번, 이름, 급여 출력 
SELECT EMPNO, ENAME, SAL
    FROM EMP MANAGER
    WHERE EXISTS (SELECT * FROM EMP WHERE MANAGER.EMPNO = MGR);
--말단사원의 모든 필드 정보 출력
SELECT * FROM EMP MANAGER
    WHERE NOT EXISTS (SELECT * FROM EMP WHERE MANAGER.EMPNO=MGR);

--부서별로 가장 급여를 많이 받는 사원의 정보(사원 번호, 사원이름, 급여, 부서번호)를 출력(IN 연산자 이용)
SELECT DEPTNO, MAX(SAL) FROM EMP GROUP BY DEPTNO;
SELECT EMPNO, ENAME, SAL, DEPTNO
    FROM EMP
    WHERE (DEPTNO, SAL) IN (SELECT DEPTNO, MAX(SAL) FROM EMP GROUP BY DEPTNO);

SELECT * FROM EMP WHERE (SAL) IN (SELECT MAX(SAL) FROM EMP GROUP BY DEPTNO); 
--위를 보완하자
--SELECT * FROM EMP WHERE (DEPTNO, SAL) IN (SELECT DEPTNO, MAX(SAL) FROM EMP GROUP BY DEPTNO); 

--직급(JOB)이 MANAGER인 사람의 속한 부서의 부서 번호와 부서명과 지역을 출력(IN)
SELECT E.DEPTNO, D.DNAME, LOC FROM EMP E, DEPT D
    WHERE E.DEPTNO=D.DEPTNO AND JOB IN (SELECT * FROM EMP WHERE JOB='MANAGER');

SELECT DEPTNO, DNAME, LOC FROM DEPT
    WHERE DEPTNO IN (SELECT DEPTNO FROM EMP WHERE JOB='MANAGER');

--연봉이 3000이상인 사람들 중 연봉 등급을 나누어서 해당 등급별 최고 연봉을 받는 사람들의 사번, 이름, 직업, 입사일, 급여, 급여등급을 출력
SELECT GRADE, MAX(SAL) FROM EMP, SALGRADE
    WHERE SAL BETWEEN LOSAL AND HISAL AND SAL>=3000 GROUP BY GRADE;


SELECT EMPNO, ENAME, HIREDATE, SAL,GRADE FROM EMP E, SALGRADE 
WHERE SAL BETWEEN LOSAL AND HISAL 
AND (GRADE, SAL) IN (SELECT GRADE, MAX(SAL) FROM EMP, SALGRADE
    WHERE SAL BETWEEN LOSAL AND HISAL AND SAL>=3000 GROUP BY GRADE);


--★REVIEW 할것
--응용심화 : 입사일 분기별로 가장 높은 연봉을 받는 사람들의 분기, 사번, 이름, JOB, 상사사번, 입사일, 급여, 상여를 출력하세요
SELECT HIREDATE, DEIL(EXTRACT(MONTH FROM HIREDATE)/3) QUARTER FROM EMP;
SELECT HIREDATE,CEIL (TO_CHAR(HIREDATE,'MM')/3) QUARTER FROM EMP;
SELECT CEIL(EXTRACT(MONTH FROM HIREDATE)/3) QUARTER, MAX(SAL) FROM EMP
    GROUP BY CEIL(EXTRACT(MONTH FROM HIREDATE)/3);
    
SELECT CEIL(EXTRACT(MONTH FROM HIREDATE)/3) QUARTER, EMPNO, ENAME, JOB,;


--SALESMAN 모든 사원들 보다 급여를 많이 받는 사원들의 이름과 급여와 직급(담당 업무)를 출력하되 영업 사원은 출력하지 않는다.(ALL이용)
SELECT ENAME, SAL, JOB FROM EMP WHERE SAL>ALL (SELECT SAL FROM EMP WHERE JOB='SALESMAN') AND JOB!='SALESMAN';

--SALESMAN 일부 어떤 한 사원보다 급여를 많이 받는 사원들의 이름과 급여와 직급(담당 업무)를 출력하되 영업 사원은 출력(ANY)
SELECT ENAME, SAL, JOB FROM EMP WHERE SAL>ANY (SELECT SAL FROM EMP WHERE JOB='SALESMAN') AND JOB!='SALESMAN';
    
--연봉이 3000미만인 사람 중에 가장 최근에 입사한 사람의 사원번호와 이름, 연봉, 입사일을 출력
SELECT DEPTNO, ENAME, SAL*12+COMM 연봉, HIREDATE 
FROM EMP
WHERE HIREDATE = (SELECT MAX(HIREDATE) FROM EMP WHERE (SAL*12+COMM)<30000);

--직급이 ‘SALESMAN’인 사원이 받는 급여의 최소 급여보다 많이 받는 사원들의 이름, 급여, 직급, 부서번호를 출력하되 부서번호가 20번인 사원은 제외한다(ANY 연산자 이용)
SELECT * FROM EMP;
SELECT ENAME, SAL, JOB, DEPTNO FROM EMP WHERE SAL>ANY(SELECT SAL FROM EMP WHERE JOB='SALESMAN')AND DEPTNO!=20;






--연습문제
-- 14. 사원 테이블에서 이름에 “T”가 있는 사원이 근무하는 부서에서 근무하는 모든 종업원에 대해
    --사원 번호,이름,급여를 출력하는 SELECT문을 작성하시오. 단 사원번호 순으로 출력하여라.
SELECT DEPTNO FROM EMP WHERE ENAME LIKE '%T%'; --서브쿼리
SELECT DEPTNO, ENAME, SAL 
    FROM EMP 
    WHERE DEPTNO IN (SELECT DEPTNO FROM EMP WHERE ENAME LIKE '%T%') ORDER BY DEPTNO;

-- 15. 사원 테이블에서 부서 위치가 Dallas인 모든 종업원에 대해 이름,업무,급여를 출력
SELECT ENAME FROM EMP E, DEPT D WHERE E.DEPTNO = D.DEPTNO AND LOC='DALLAS'; --서브쿼리
SELECT ENAME, JOB, SAL 
    FROM EMP 
    WHERE ENAME IN (SELECT ENAME FROM EMP E, DEPT D WHERE E.DEPTNO = D.DEPTNO AND LOC='DALLAS');

--★review
-- 16. EMP 테이블에서 King에게 보고하는 모든 사원의 이름과 급여를 출력하는 SELECT문
SELECT E1.ENAME FROM EMP E1, EMP E2 WHERE E1.MGR=E2.EMPNO AND E1.MGR='7839'; --서브쿼리
SELECT ENAME, SAL 
    FROM EMP 
    WHERE ENAME IN (SELECT E1.ENAME FROM EMP E1, EMP E2 WHERE E1.MGR=E2.EMPNO AND E1.MGR='7839');

-- 17. 사원 테이블에서 SALES부서 사원의 이름,업무를 출력하는 SELECT문을 작성하시오.
SELECT E.ENAME FROM EMP E, DEPT D WHERE  E.DEPTNO = D.DEPTNO AND DNAME = 'SALES'; --서브쿼리
SELECT ENAME, JOB 
    FROM EMP 
    WHERE ENAME IN(SELECT E.ENAME FROM EMP E, DEPT D WHERE  E.DEPTNO = D.DEPTNO AND DNAME = 'SALES');

-- 18. 사원 테이블에서 월급이 부서 30의 최저 월급보다 높은 사원을 출력
SELECT MIN(SAL) FROM EMP WHERE DEPTNO='30';  --서브쿼리
SELECT ENAME 
    FROM EMP 
    WHERE SAL>ANY(SELECT SAL FROM EMP WHERE DEPTNO='30');

-- 19. 부서 10에서 부서 30의 사원과 같은 업무를 맡고 있는 사원의 이름과 업무를 출력
SELECT JOB FROM EMP WHERE DEPTNO='30';
SELECT ENAME, JOB 
    FROM EMP
    WHERE DEPTNO = '10' AND JOB IN(SELECT JOB FROM EMP WHERE DEPTNO='30');

-- 20. 사원 테이블에서 FORD와 업무도 월급도 같은 사원의 모든 정보를 출력
SELECT JOB, SAL FROM EMP WHERE ENAME = 'FORD';
SELECT * 
    FROM EMP 
    WHERE (JOB, SAL)=(SELECT JOB, SAL FROM EMP WHERE ENAME = 'FORD')AND ENAME<>'FORD';

-- 21. 이름이 JONES인 직원의 JOB과 같거나 
    --월급이 FORD 월급 이상인 사원의 정보를 이름,업무,부서번호,급여를 출력하는 SELECT문을 작성.
    -- 단, 업무별 알파벳 순, 월급이 많은 순으로 출력하여라.

SELECT ENAME, JOB, DEPTNO, SAL FROM EMP 
    WHERE JOB=(SELECT JOB FROM EMP WHERE ENAME='JONES')
    OR SAL>=(SELECT SAL FROM EMP WHERE ENAME='FORD')
    AND ENAME!='JONES' AND ENAME!='FORD'
    ORDER BY JOB, SAL DESC;

--★
-- 22. 사원 테이블에서 SCOTT 또는 WARD와 월급이 같은 사원의 정보를 이름,업무,급여를 출력하는 SELECT문을 작성하시오.

--SELECT SAL FROM EMP WHERE SAL=(SELECT SAL FROM EMP WHERE ENAME='SCOTT') OR SAL=(SELECT SAL FROM EMP WHERE ENAME='WARD');

SELECT SAL FROM EMP WHERE ENAME IN ('SCOTT','WARD');--서브쿼리
SELECT ENAME, JOB, SAL 
    FROM EMP 
    WHERE SAL IN(SELECT SAL FROM EMP WHERE ENAME IN ('SCOTT','WARD')) AND ENAME!='SCOTT' AND ENAME !='WARD';


-- 23. 사원 테이블에서 CHICAGO에서 근무하는 사원과 같은 업무를 하는 사원들의 이름,업무를 출력하는 SELECT문을 작성하시오.
SELECT JOB FROM EMP E, DEPT D WHERE E.DEPTNO = D.DEPTNO AND LOC='CHICAGO';
SELECT ENAME, JOB 
    FROM EMP 
    WHERE JOB IN(SELECT JOB FROM EMP E, DEPT D WHERE E.DEPTNO = D.DEPTNO AND LOC='CHICAGO');

-- 24. 사원 테이블에서 부서별로 월급이 평균 월급보다 높은 사원을 사원번호,이름,급여를 출력하는 SELECT문을 작성하시오.
SELECT DEPTNO, AVG(SAL) FROM EMP GROUP BY DEPTNO; --서브쿼리는 이것으로 두면 안됨.
SELECT AVG(SAL) FROM EMP WHERE DEPTNO=E.DEPTNO --이런 서브쿼리지만, 이것은 따로는 실행되지 않는다.

SELECT DEPTNO, ENAME, SAL FROM EMP E
    WHERE SAL>(SELECT AVG(SAL) FROM EMP WHERE DEPTNO=E.DEPTNO);

SELECT DEPTNO, ENAME, SAL, TRUNC((SELECT AVG(SAL) FROM EMP WHERE DEPTNO=E.DEPTNO)) 부서평균  FROM EMP E
    WHERE SAL>(SELECT AVG(SAL) FROM EMP WHERE DEPTNO=E.DEPTNO);

-- 25. 사원 테이블에서 업무별로 월급이 평균 월급보다 낮은 사원을 부서번호,이름,급여를 출력하는 SELECT문을 작성하시오.
SELECT DEPTNO, AVG(SAL) FROM EMP GROUP BY DEPTNO;

SELECT DEPTNO, ENAME, SAL FROM EMP E
    WHERE SAL<(SELECT AVG(SAL) FROM EMP WHERE DEPTNO=E.DEPTNO);

-- 26 사원 테이블에서 적어도 한 명 이상으로부터 보고를 받을 수 있는 사원을 업무,이름,사원번호,부서번호를 출력(단, 부서번호 순으로 오름차순 정렬)
SELECT JOB,ENAME,EMPNO,DEPTNO 
    FROM EMP MANAGER
    WHERE EXISTS(SELECT * FROM EMP WHERE MANAGER.EMPNO=MGR) ORDER BY DEPTNO;

SELECT JOB,ENAME,EMPNO,DEPTNO 
    FROM EMP MANAGER
    WHERE EXISTS(SELECT * FROM EMP W WHERE MANAGER.EMPNO=W.MGR) ORDER BY DEPTNO;

-- 27. 사원 테이블에서 말단 사원의 사원번호, 이름, 업무, 부서번호를 출력하는 SELECT문을 작성하시오.
SELECT EMPNO, ENAME, JOB, DEPTNO
    FROM EMP MANAGER
    WHERE NOT EXISTS (SELECT * FROM EMP WHERE MANAGER.EMPNO=MGR);
    
--IN을 쓸때는 NOT을 사용하면 NULL때문에 문제가 생길 수 있으므 NULL을 제거하던가 IN을 쓰지 말아야한다.
    
    

    
    

